### ISSUE TITLE
Resource name GraphQlResolver ** is non alphanumeric. in v1.0.0

### ISSUE THREAD

**Issue by Gbahaa** [sid88in/serverless-appsync-plugin#98] opened 2018-06-08 01:01 UTC
At first , thanks for your great efforts to bring this plugin.

After upgrading to v1.0.0, I got the error of **Resource name GraphQlResolver ** is non alphanumeric**. in _v1.0.0_. It was working in earlier versions though. 

This is an example: 
```
- dataSource: createPosts
  type: Mutation
  field: create_posts
  request: "create-req.txt"
  response: "common-res.txt"
- dataSource: webhookCreatePosts
  type: Mutation
  field: w_create_posts
  request: "create-req.txt"
  response: "common-res.txt"
```

Error is: 
Resource name GraphQlResolver w_create_posts is non alphanumeric.

It accepts [create_posts] but not [w_create_posts] while both are valid graphql field names. 

As I implementing an automatic schema generator from a database, I am worried that a user may use such names for their fields. 

Any help is appreciated.

By the way, currently, I replaced w_create_posts by webhookCreate_posts and it worked.
Regards

**Comment by ajmath** [comment] 2018-06-08 12:59
Sorry about that.  This is a bug caused by a missing global flag on a regex.  A fix is inbound

**Closed** 2018-06-08 16:02 UTC
